#!/usr/bin/env python
from jModules.Database       import Database
from modules.WallpaperSetter import WallpaperSetter
import argparse
import json
import os
import random

_scriptRoot = os.path.dirname(os.path.realpath(__file__))
_scriptName = _scriptRoot.split('/')[-1]
_namespace  = _scriptName

dbFile     = "%s/db.sqlite"        % _scriptRoot
schemaFile = "%s/schema.json"      % _scriptRoot
configFile = "%s/config.json"      % _scriptRoot

def main():

    parser = argparse.ArgumentParser(description="A script for changing my wallpaper.")

    parser.add_argument(
            '--debug',
            action='store_true',
            default=False,
            help='Enable debug logging'
            )

    args = parser.parse_args()

    try:
       with open(configFile, 'r') as file:
           config = json.loads(file.read())
    except FileNotFoundError:
        print('Please copy %s.sample to %s to get started.' % (configFile, configFile))
        exit(1)



    database = Database(databaseFile=dbFile, schema=schemaFile, debug=args.debug)
    wpSetter = WallpaperSetter(config=config, database=database, debug=args.debug)

    ## Testing
    #columns = ["path", "res", "profile", "checksum", "added", "seen"]
    #values  = ["/tmp/test's \"here22\".png",
    #           "1920x1080",
    #           "AABBCC",
    #           "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    #           "Wed 27 Nov 2024 11:28:50 AEDT",
    #           "Wed 25 Nov 2024 13:17:55 AEDT"]
    #database.insert(columns=columns, values=values)

    # Check whether or not we should use a spanning image 
    # Roll for whether we should try a single spanning image, or one image per display

    roll = random.randint(1, 100)
    if roll <= config['spanChancePercent']:
        span = True
        if args.debug:
            print("Successfully rolled for a spanning image.")
    else:
        span = False

    wpSetter.run(mode=config['bgmode'], span=span)

if __name__ == "__main__":
    main()

